# Generated by Django 4.2.7 on 2026-01-27 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0002_alter_corporatemission_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatetrack',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corporatetrack',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teamtrackassignment',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.corporatetrack'),
        ),
    ]
