# Generated by Django 5.2.7 on 2026-01-24 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('subtask_completed', 'Subtarefa concluída'), ('mission_completed', 'Missão concluída'), ('level_up', 'Subiu de nível'), ('achievement', 'Conquista desbloqueada')], max_length=30)),
                ('message', models.CharField(max_length=220)),
                ('xp_delta', models.IntegerField(default=0)),
                ('track', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
