# Generated by Django 4.2.7 on 2026-01-25 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='achievement',
            name='key',
            field=models.SlugField(default='temp_key', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='code',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='earned_at',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
