# Generated by Django 4.2.7 on 2026-01-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_achievement_unique_together_achievement_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('xp_multiplier', models.FloatField(default=1.0)),
            ],
        ),
    ]
