# Generated by Django 4.2.7 on 2026-01-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_setup_groups_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.CharField(choices=[('user', 'Usuário'), ('mentor', 'Mentor'), ('company', 'Empresa')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role_approved',
            field=models.BooleanField(default=False),
        ),
    ]
