# Generated by Django 4.2.7 on 2026-01-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_requested_role_user_role_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
