# Generated by Django 4.2.7 on 2026-01-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avataritem',
            name='rarity',
            field=models.CharField(choices=[('common', 'Comum'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Lendário')], default='common', max_length=20),
        ),
    ]
