# Generated by Django 4.2.7 on 2026-01-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_avataritem_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avataritem',
            name='image_path',
        ),
        migrations.AddField(
            model_name='avataritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/items/'),
        ),
    ]
