# Generated by Django 4.2.7 on 2026-01-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_remove_avataritem_image_path_avataritem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='avataritem',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição do item (história, efeito ou curiosidade)'),
        ),
    ]
