# Generated by Django 4.2.7 on 2026-01-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='ompleted_at',
            new_name='completed_at',
        ),
    ]
